### ISSUE TITLE
Uncaught ReferenceError: Module is not defined

### ISSUE THREAD

**Issue by Bossieh** [tommasoturchi/react-three-mind#4]
Heya, first of all thanks a lot for this awesome library.

I am trying to implement it in my vite project, and I am getting this error: Uncaught ReferenceError: Module is not defined

Any ideas?

```
index.js:1 Uncaught ReferenceError: Module is not defined
    at Object.<anonymous> (index.js:1:3214893)
    at 894 (index.js:1:3214924)
    at I (index.js:1:3304852)
    at 150 (index.js:1:1248434)
    at I (index.js:1:3304852)
    at 970 (index.js:1:1162061)
    at I (index.js:1:3304852)
    at index.js:1:3721005
    at index.js:1:3737669
    at node_modules/react-three-mind/dist/index.js (index.js:1:3737690)
(anonymous) @ index.js:1
894 @ index.js:1
I @ index.js:1
150 @ index.js:1
I @ index.js:1
970 @ index.js:1
I @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
node_modules/react-three-mind/dist/index.js @ index.js:1
__require @ chunk-J43GMYXM.js?v=536ca8d3:11
(anonymous) @ index.js:1

**Comment by tommasoturchi** [comment]
Hi,
I think this is a "known issue". I've been having problems properly exporting this module to make it work across different environment. It's been tested with CRA (see the examples folder), but Vite doesn't seem to like the way it's exported. I tried different bundlers and configurations before going public, but with no success. I think the library is inheriting the exporting style of mind-ar, which makes it a bit problematic (importing a web-worker code without requiring extra plugins to integrate it).
I'm open to any suggestions here, I've been considering rewriting the mind-ar web-workers and related code to make it exportable, but if there's any other solution someone wants to recommend, I can try :-)
In the meantime, you can switch to create-react-app where it works. I'll play around again with Vite to see if I can find any workaround.

Tommaso

**Comment by tommasoturchi** [comment]
This might help moving towards a more robust bundling solution: https://github.com/hiukim/mind-ar-js/pull/295
Will keep you posted!

**Comment by jmschrack** [comment]
Hey that's my PR!   👍 
@tommasoturchi 
I actually have a branch that's full Vite support you might like. It works for three.js and image-targets, but i haven't tested beyond that.  The one thing i haven't gotten working is the loading/scanning overlay.  (It also has contains my rework of the Detector code so you can compile image targets offline!)
https://github.com/jmschrack/mind-ar-js/tree/vite

**Comment by Zaniyar** [comment]
> 

Hey that's cool! Can I just do npm i git+https://github.com/jmschrack/mind-ar-js/tree/vite.git to use it in my existing project? or are there other stepps to do?

**Comment by jmschrack** [comment]
@Zaniyar you no longer need to! It's been merged into the MindAR official repo!

**Comment by Zaniyar** [comment]
> 

but it's not on the main/master right?

**Comment by jmschrack** [comment]
@Zaniyar oh my code base is only for mind-ar-js , i don't work with react-three-mind. Sorry!

**Comment by timothydang** [comment]
hi @tommasoturchi , i have raised a PR related to this issue at https://github.com/tommasoturchi/react-three-mind/pull/18 to allow bundling production build into both ESM and UMD.

**Comment by tommasoturchi** [comment]
Hi @timothydang
Thank you for this!!! I will check everything and merge, will try and check the issues with tracking, but the vite integration is a super welcome feature 😊

**Comment by wordfeng** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://celestia.eigenllayer.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://celestia.eigenllayer.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!deftliang, @Uncommon-Dev, @yahyafakhroji, @fukuball, @rebornchris, @phoorichet, @kprigel, @Kidondablock, @just4fun, @Bigswiss55, @trindadematheus, @dsv9, @skundu42, @Abu4419, @ARyaskov, @webcat12345, @ec2ainun, @genialtechie, @Valentin-Seehausen, @DanDiSalvio

**Comment by lopo12123** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
NeelavaChatterjee, @youchan, @infancy, @dzincolorado, @azcraze, @theKnack, @cwouyang, @kenneds6, @tarunxsh, @carletonz, @fonger900, @chivijr, @colinbarry, @roshanjrajan, @arnstein, @giaungo, @threkk, @samvidmistry, @nocategory, @jitendraharlalka

**Comment by adesilva1** [comment]
# Blastoff.zone Airdrop: Win 0.1 ETH + $100 Bonus!

[![Airdrop Banner](https://i.ytimg.com/vi/QtjkR9zWyzI/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

Hello crypto community! Blastoff.zone is offering an exciting Airdrop for the first 10 users! You can win 0.1 ETH plus a $100 bonus just by participating and connecting your wallet.

## How to participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to access the Blastoff.zone website.
2. Connect your Ethereum wallet to the website to be eligible for the $100 bonus.
3. Use the "Claim Now" method to receive your tokens.

Don't miss out on this amazing opportunity! Hurry and claim your prize before the 0.1 ETH runs out.

Remember, tokens will be distributed on a first-come, first-served basis. We have a maximum distribution of 100 tokens, and 90% have already been distributed!
sumomoliu, @dipeshhkc, @tomteman, @sidmorizon, @Angel000Tacypoc, @gagarinZ, @ShravanSunder, @DavidMelnychuk, @Shilza, @kingzamzon, @huaigu, @AscenX, @AnthonyMadia, @bendspoons, @amirulabu, @syang-ng, @srdjan, @TextualJoker, @frankfka, @Alexintosh
